$("#fullName").val("Timmy Mallet");
$("#dobDay").val("19");
$("#dobMonth").val("10");
$("#dobYear").val("1976");
$("#address1").val("1 Curtain Pole");
$("#jobTitle").val("Interaction Designer");
$("#employer").val("McDonalds Restaurant");
$("#address1").val("1 Fisherman's Path");
$("#manager").val("Yale Fortescue");
$("#managerContactNo").val("0987 654 3213");
$("#daysPerWeek").val("5");
$("#hoursPerWeek").val("5");
$("#hoursPerWeek").val("37.5");
$("#description").val("Fybromyalgia");
$("#radio-indent-3partyyes").trigger('click');
$("#contactMethodEmailLabel").trigger('click');
$("#contactMethodPhoneLabel").trigger('click');
$("#email").val("tom.jones@thevallys.com");
$("#phoneNumber").val("0987 654 3213");
$('textarea').val("Phasellus interdum metus nibh, nec vestibulum leo commodo non. Vivamus lobortis ex nisl, quis molestie quam consectetur vitae. Vestibulum aliquet aliquet felis, eget vulputate dui consectetur vel.");
